pin/unpin driver from car/driver's list of cars
RuslanShaykhutdinov/AutoPark pull request #17
Opened 2022-03-21 20:03 UTC by SanjarU1337

2022-03-24 07:12 UTC, RuslanShaykhutdinov requested changes
Исправь и не создавай новый пул реквест просто сделай пуш в эту же ветку

2022-03-24 07:12 UTC, RuslanShaykhutdinov commented on src/main/java/com/autoPark/AutoPark/controller/DriverController.java
> +    public ResponseEntity<RestError> unpindriver(@RequestBody String json){
все тоже самое что и в прошлом методе

2022-03-24 07:12 UTC, RuslanShaykhutdinov commented on src/main/java/com/autoPark/AutoPark/controller/DriverController.java
> +        try {
нужно добавить проверку на категорию, водитель может водить только одну определенную категорию машин

2022-03-25 19:48 UTC, dvur0g commented on src/main/java/com/autoPark/AutoPark/controller/DriverController.java
> +        String passportId = jo.get("PassportId").getAsString();
+1

2022-03-25 19:56 UTC, dvur0g commented on src/main/java/com/autoPark/AutoPark/controller/DriverController.java
> +    @GetMapping(value = "/driverCars")
https://github.com/RuslanShaykhutdinov/AutoPark/pull/17#discussion_r833963095

2022-03-25 19:56 UTC, dvur0g commented on src/main/java/com/autoPark/AutoPark/controller/DriverController.java
> +@RequestMapping(value = "/Driver")
https://github.com/RuslanShaykhutdinov/AutoPark/pull/17#discussion_r833963095

2022-03-25 20:03 UTC, dvur0g commented on src/main/java/com/autoPark/AutoPark/controller/DriverController.java
> +        String passportId = jo.get("PassportId").getAsString();
переменные в json тоже с маленькой буквы

2022-03-25 20:03 UTC, dvur0g commented on src/main/java/com/autoPark/AutoPark/controller/DriverController.java
> +        String carId = jo.get("CarId").getAsString();
переменные в json тоже с маленькой буквы

2022-03-25 21:30 UTC, closed without merging